### ISSUE TITLE
Error compiling for Arduino Mega with <SD.h> included..

### ISSUE THREAD

**Issue by shane84948** [chillibasket/sd-config-file#1]
Hello,

First, thank you, this is precisely what I was looking for. There is nothing wrong with your code when I compile it separately but when I incorporate it with my own, I get an error message.

 Im sure its because I have I have #include <SD.h>
I have SD.h because my "datalog" file on the sd card. I write to it using SD.open and Sd.File.println. This is all through my sketch. When I comment out <SD.h> everything seems to compile fine, but I get these errors.

AquaOTA:279:8: error: 'SD' was not declared in this scope
   if (!SD.begin(SDCS)) {

AquaOTA:291:12: error: 'SD' was not declared in this scope
   SdFile = SD.open("ConfigFile.txt", FILE_WRITE);

How can I incorporate a simple 

  if (DataLog == ON) {
        SdFile = SD.open("DATALOG.txt", FILE_WRITE);

    // if the file is available, write to it:
    if (SdFile) {
      Serial.println("Data Log started");
      SdFile.print(now.toString(date1));
      SdFile.print(now.toString(date1));
      SdFile.print(",");
      SdFile.print(now.toString(time1));
      SdFile.print(","); //Move to next column using a ","
      SdFile.println("Data Log ON");
      SdFile.println(); //End of Row move to next row
      SdFile.close(); //Close the file
    }

Thanks in advance for your help.

**Comment by chillibasket** [comment]
My code uses the "SdFat.h" library to read and write to the SD card (see [https://github.com/greiman/SdFat](https://github.com/greiman/SdFat)). The built-in Arduino "SD.h" code internally uses this same library, but an older version of it. This is causing the incompatibility that you experienced. One solution would be to update your sketch code to use the new "SdFat.h" library instead. Most of the commands to read and write are almost the same:

- Replace `#include <SD.h>` with `#include <SdFat.h>`
- Add a declaration of the SD object to the top of the sketch: `SdFat32 sd;`
- Replace all references to `SD` with `sd`, for example `SD.open("ConfigFile.txt", FILE_WRITE)` becomes `sd.open("ConfigFile.txt", FILE_WRITE)`
- Use `File32 SdFile;` instead of `File SdFile;` when defining the file variable.

**Comment by shane84948** [comment]
Thank you for the help. Everything compiles and works as expected!!
